server:
  port: 8080

spring:
  application:
    name: bank
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      ttl-minutes: 60
  jpa:
    hibernate:
      ddl-auto: update

axon:
  axonserver:
    servers: ${AXON_SERVER_URL:localhost}
    context: default
  serializer:
    messages: jackson
    events: jackson
    general: jackson

jwt:
  secret: 301ca77a-654e-426a-8028-b8d7f735b7a6
  expirationTime: 3600000

logging:
  level:
    root: WARN

clientorigin: http://localhost:4200