server:
  port: 8080
spring:
  application:
    name: bank
  datasource:
    url: jdbc:h2:mem:transactionmonitor
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: 301ca77a-654e-426a-8028-b8d7f735b7a6
  expirationTime: 3600000
clientorigin: http://localhost:4200