server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: bank
  datasource:
    url: jdbc:h2:mem:bank
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      ttl-minutes: 60
  jpa:
    hibernate:
      ddl-auto: update

axon:
  axonserver:
    servers: ${AXON_SERVER_URL:localhost}
    context: default
  serializer:
    messages: jackson
    events: jackson
    general: jackson

jwt:
  secret: 301ca77a-654e-426a-8028-b8d7f735b7a6
  expirationTime: 3600000

logging:
  level:
    root: WARN

clientorigin: http://localhost:4200